#!/bin/bash

set -e


cd /root/NasX86_config/SysLib/xmlrpc/ && ./configure && pwd
cd /root/NasX86_config/SysLib/cups-1.4.4/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gdbm-1.10/ && ./configure && pwd
cd /root/NasX86_config/SysLib/lcms2-2.6/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gcc-4.9.2-stdc++/libstdc++-v3/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gcc-4.9.2-stdc++/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libusb-0.1.12/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libnfsidmap-0.23/ && ./configure && pwd
cd /root/NasX86_config/SysLib/jpeg-6b-src/ && ./configure && pwd
cd /root/NasX86_config/SysLib/ijs-0.35/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libharu-2.1.0/ && ./configure && pwd
cd /root/NasX86_config/SysLib/fcgi-2.4.0/perl/ && ./configure && pwd
cd /root/NasX86_config/SysLib/fcgi-2.4.0/ && ./configure && pwd
cd /root/NasX86_config/SysLib/jrtplib-3.3.0/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gutenprint-5.2.10/ && ./configure && pwd
cd /root/NasX86_config/SysLib/librsync-0.9.7/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libiconv-1.12/libcharset/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libiconv-1.12/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libupnp-1.6.18/ && ./configure && pwd
cd /root/NasX86_config/SysLib/poppler-0.19.4/ && ./configure && pwd
cd /root/NasX86_config/SysLib/eventlog-0.2.7/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libevent-1.4.12-stable/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libupnp-1.4.1/ && ./configure && pwd
cd /root/NasX86_config/SysLib/expat-2.0.0/ && ./configure && pwd
cd /root/NasX86_config/SysLib/pam-0.99.7.1/Linux-PAM/ && ./configure && pwd
cd /root/NasX86_config/SysLib/giflib-4.1.3/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libupnp-1.6.19/ && ./configure && pwd
cd /root/NasX86_config/SysLib/fontconfig-2.11.1/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libxml2-2.9.2/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gd-1.8.4/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libnfsidmap-0.25/ && ./configure && pwd
cd /root/NasX86_config/SysLib/jpeg-6b/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gdbm-1.8.3/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libid3tag-0.15.1b/ && ./configure && pwd
cd /root/NasX86_config/SysLib/cups-1.6.4/ && ./configure && pwd
cd /root/NasX86_config/SysLib/ffmpeg/ && ./configure && pwd
cd /root/NasX86_config/SysLib/cups-filters-1.0.20/ && ./configure && pwd
cd /root/NasX86_config/SysLib/zlib-1.2.8/ && ./configure && pwd
cd /root/NasX86_config/SysLib/fontconfig-2.10.0/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libgpg-error-1.6/ && ./configure && pwd
cd /root/NasX86_config/SysLib/attr-2.4.47/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gnutls-2.6.2/ && ./configure && pwd
cd /root/NasX86_config/SysLib/e2fsprogs-1.42.5/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libtirpc-0.3.0/ && ./configure && pwd
cd /root/NasX86_config/SysLib/librpcsecgss-0.19/ && ./configure && pwd
cd /root/NasX86_config/SysLib/rlog-1.4/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libtool-1.5.24/ && ./configure && pwd
cd /root/NasX86_config/SysLib/popt-1.14/ && ./configure && pwd
cd /root/NasX86_config/SysLib/fuse-2.9.2/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libgcrypt-1.4.3/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gnupg-1.4.19/ && ./configure && pwd
cd /root/NasX86_config/SysLib/db-4.8.30/dist/ && ./configure && pwd
cd /root/NasX86_config/SysLib/openldap-2.4.7/ && ./configure && pwd
cd /root/NasX86_config/SysLib/cyrus-sasl-2.1.22/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libusb-compat-0.1.4/ && ./configure && pwd
cd /root/NasX86_config/SysLib/freetype-2.3.7/ && ./configure && pwd
cd /root/NasX86_config/SysLib/ntfs-3g-1.2412/ && ./configure && pwd
cd /root/NasX86_config/SysLib/Linux-PAM-1.2.1/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gd-2.0.34/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libnl-1.1.4/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libxml2-2.6.30/ && ./configure && pwd
cd /root/NasX86_config/SysLib/liboop-1.0/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libcsv-3.0.2/ && ./configure && pwd
cd /root/NasX86_config/SysLib/glib-2.24.2/ && ./configure && pwd
cd /root/NasX86_config/SysLib/nettle-2.7.1/ && ./configure && pwd
cd /root/NasX86_config/SysLib/ncurses-5.5/ && ./configure && pwd
cd /root/NasX86_config/SysLib/pcre-8.36/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libcommon-0.98.10.1/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libusb-1.0.9/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libidn-1.25/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libxslt-1.1.22/ && ./configure && pwd
cd /root/NasX86_config/SysLib/json-c-0.9/ && ./configure && pwd
cd /root/NasX86_config/SysLib/readline-5.2/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libffi-3.2.1/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libtasn1-1.6/ && ./configure && pwd
cd /root/NasX86_config/SysLib/krb5-1.13/src/ && ./configure && pwd
cd /root/NasX86_config/SysLib/sqlite-3.4.1/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libuuid-1.0.3/ && ./configure && pwd
cd /root/NasX86_config/SysLib/ImageMagick-6.6.1-5/ && ./configure && pwd
cd /root/NasX86_config/SysLib/flex-2.5.39/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libpng-1.2.15/ && ./configure && pwd
cd /root/NasX86_config/SysLib/acl-2.2.49/ && ./configure && pwd
cd /root/NasX86_config/SysLib/libgssglue-0.4/ && ./configure && pwd
cd /root/NasX86_config/SysLib/gdbm-1.11/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/nut-2.2.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/wget-1.11.4/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/nut-2.6.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/neon-0.30.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/screen-4.0.3/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/thin-provisioning-tools-v0.4.1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/nut-2.0.3/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/wget-1.10/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/radvd-1.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/coreutils-6.7/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/LVM2.2.02.105/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/curl-7.21.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ftpcopy-0.4.8/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/mt-daapd-0.2.4/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/mt-daapd-svn-1696/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/wget-1.16/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/sg3_utils-1.32/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ppp-2.4.7/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/cryptsetup-1.0.6/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/stunnel-4.15/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/netkit-ftp-0.17/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/vim72/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/dhcpv6-1.1.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ecryptfs-utils-74/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/freeradius-server-2.2.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/encfs-1.7.4/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/bluez-4.60/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/aumix-2.9.1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/tar-1.18/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/centerim-4.22.10/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/mlocate-0.25/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/openssh-6.9p1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/iproute2-2.6.39/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/djmount-0.71/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ntp-4.2.8/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/inotify-tools-3.14/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/dhcpcd-1.3.22-p14/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/libcgroup-0.41/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/rsync-3.0.7/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/stunnel-4.32/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/mktemp-1.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/usbutils-0.11/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/util-linux-2.12q/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/mt-daapd-0.2.4.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/bind-9.10.1-P2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/openldap-2.4.23/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/usbutils-0.72/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ez-ipupdate-3.0.10/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/curl-7.43.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ppp-2.4.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/gnupg-1.4.13/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/net-snmp-5.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/cifs-utils-5.6/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/syslog-ng-2.0.9/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ethtool-4.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/sg3_utils-1.29/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/cryptsetup-1.5.1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/rpcbind-0.2.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/curlftpfs-0.9.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/xpdf-3.04/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/curl-7.42.1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/apcupsd-3.14.10/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/unzip60/unix/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ipmitool-1.8.15/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/irqbalance-1.0.6/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/avahi-0.6.30/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/nss_ldap-265/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/apcupsd-3.13.9/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/timespan-2.1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/bash-3.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/dirsync-1_11/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/davfs2-1.5.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/apcupsd-3.14.4/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ffmpeg-0.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/rsyslog-4.4.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/openssh-7.0p1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/gmediaserver-0.11.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/gnupg-1.4.7/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/apcupsd-3.10.15/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/shadow-4.1.4/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/udev-140/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/wide-dhcpv6-20080615.patched/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/wide-dhcpv6-20080615/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/bash-3.2.48/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/ethtool-6/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/libqb-0.16.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/parted-2.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/util-linux-2.19/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/alsa-utils-1.0.27.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/grep-2.5.1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/systemtap-2.6/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/psmisc-22.20/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/dbus-1.4.16/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/parted-3.1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/proftpd-1.3.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/alsa-lib-1.0.27.2/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/nfs-utils-1.2.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/pptpd-1.4.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/iptables-1.4.21/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/tar-1.22/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/netatalk-3.0.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/openvpn-2.3.6/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/Python-2.7.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/procps-ng-3.3.11/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/drbd-utils-8.9.0/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/intltool-0.41.1/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/lzo-2.05/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/samba-4.0.5/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/zip30/unix/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/libdaemon-0.14/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/clamav-0.98.6/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/elfutils-0.148/ && ./configure && pwd
cd /root/NasX86_config/SysUtil/qrencode-3.4.4/ && ./configure && pwd
