cc_library(
  name = "zlib",
  srcs = glob(["*.c"]),
  hdrs = glob(["*.h"]),
  visibility =["//visibility:public"],
  copts = [
    "-Wno-unused-variable",
    "-Wno-implicit-function-declaration",
  ],
)
